export enum TokenTypes {
  ID = 'ID',
  NUMBER = 'NUMBER',
  PLUS_SYMBOL = 'PLUS_SYMBOL',
  MINUS_SYMBOL = 'MINUS_SYMBOL',
  MULTIPLICATION_SYMBOL = 'MULTIPLICATION_SYMBOL',
  DIVISION_SYMBOL = 'DIVISION_SYMBOL',
}
