export enum Keywords {
  PROGRAM = 'program',
  PROCEDURE = 'procedure',
  VAR = 'var',
  BEGIN = 'begin',
  END = 'end',
  IF = 'if',
  THEN = 'then',
  ELSE = 'else',
  WHILE = 'while',
  DO = 'do',
  TRUE = 'true',
  FALSE = 'false',
  DIV = 'div',
  AND = 'and',
  OR = 'or',
  NOT = 'not',
}
